name: "Gradle build"
permissions: {}
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: "Gradle build"
    runs-on: ubuntu-latest
    env:
      GRADLE_MICROG_VERSION_WITHOUT_GIT: 1

    steps:
      - name: "Checkout sources"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Setup Java"
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: "Cache Gradle"
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: "Gradle Wrapper validation"
        uses: gradle/actions/wrapper-validation@v4

      - name: "Setup Gradle"
        uses: gradle/actions/setup-gradle@v4

      - name: "Inspect Gradle tasks"
        run: "./gradlew tasks"

      - name: "Build APK"
        run: "./gradlew assembleRelease"

      - name: "Upload APK"
        uses: actions/upload-artifact@v3
        with:
          name: apks
          path: app/build/outputs/apk/release/*.apk
